### PR TITLE
Fix: Make `SignWithSecretKey` less risky

### LINKED ISSUE #250: `SignWithSecretKey` is risky
# Summary

The backend exposes a method `SignWithSecretKey` for Filecoin messages. There are some checks in that method, but it'd be better not to semi-blindly sign any message but to generate it on the backend with safe input, e.g., nonce.

# Completion Criteria

- [ ] Change the backend method `SignWithSecretKey` to something more specific and better checked, i.e., `SignedFilTransfer`.

# Additional Links & Resources

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Introduce `signed_fil_transfer` which signs a message with the given `nonce`.

## Reference issue to close (if applicable)

Closes #250 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation. All new code
      adheres to the team's
      [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [X] I have added tests that prove my fix is effective or that my feature works
      (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes
      should be reflected in this document.

[1]: https://github.com/ChainSafe/forest-explorer/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by hanabi1224 — DISMISSED** [review]

File: src/faucet/controller.rs [hunk 1]
```diff
@@ -217,27 +217,26 @@ impl FaucetController {
...
                         let nonce = rpc.mpool_get_nonce(from).await?;
-                        let mut msg = message_transfer(from, addr, info.drip_amount().clone());
-                        msg.sequence = nonce;
-                        let msg = rpc.estimate_gas(msg).await?;
-                        match sign_with_secret_key(LotusJson(msg.clone()), info).await {
-                            Ok(LotusJson(smsg)) => {
-                                let cid = rpc.mpool_push(smsg).await?;
+                        let raw_msg = message_transfer(from, addr, info.drip_amount().clone());
+                        let msg = rpc.estimate_gas(raw_msg).await?;
+                        match signed_fil_transfer(LotusJson(msg), nonce, info).await {
```
Comment (LesnyRumcajs) [inline src/faucet/controller.rs:230]: @sudo-shashank, can you please explain how this change mitigates the issue?

Comment (sudo-shashank) [reply src/faucet/controller.rs]: fixed now by generating the message in backend

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]
Let's have some documentation around the new methods.

File: src/utils/message.rs [hunk 2]
```diff
@@ -3,16 +3,36 @@ use fvm_shared::message::Message;
...
+        to,
+        value,
+        0,
+        TokenAmount::from_atto(0),
+        TokenAmount::from_atto(0),
+        0,
+    )
+}
+
+pub fn create_message(
```
Comment (LesnyRumcajs) [inline src/utils/message.rs:17]: Let's have some docs for this as well. The name could also be more informative; `message` is ambiguous.

File: src/utils/message.rs [hunk 3]
```diff
@@ -2,17 +2,39 @@ use fvm_ipld_encoding::RawBytes;
...
+        value,
+        0,
+        TokenAmount::from_atto(0),
+        TokenAmount::from_atto(0),
+        0,
+    )
+}
+
+/// Creates a new transfer message with specified values for gas and sequence.
+pub fn message_transfer_custom(
```
Comment (LesnyRumcajs) [inline src/utils/message.rs:19]:
```suggestion
pub fn message_transfer_native(
```
I think we should make a distinction between native FIL messages and Ethereum ones.

Comment (sudo-shashank) [reply src/utils/message.rs]: done

File: src/faucet/server.rs [hunk 4]
```diff
@@ -38,6 +44,32 @@ pub async fn secret_key(faucet_info: FaucetInfo) -> Result<Key, ServerFnError> {
...
+            cid.to_bytes().as_slice(),
+        )
+        .map_err(ServerFnError::new)?;
+        Ok(LotusJson(SignedMessage {
+            message: msg,
+            signature: sig,
+        }))
+    })
+    .await
+}
```
[the remark this answers is not in the document]
Comment (sudo-shashank) [reply src/faucet/server.rs:71]: It's not risky as it is no more exposed or registered in a route and is used only in backend by `SignedFilTransfer`.

[the remark this answers is not in the document]
Comment (LesnyRumcajs) [reply src/faucet/server.rs:71]: The main complaint is that it's not unit tested (and not tested at all, even in `k6` tests). We need to figure out how to test this properly. It's an existing issue so we can tackle it in a separate PR. Feel free to create an issue around this @sudo-shashank .

**Review by LesnyRumcajs — APPROVED** [review]
