### PR TITLE
Fix: Unvalidated gas values in signed_fil_transfer

### LINKED ISSUE #274: Unvalidated gas values in `signed_fil_transfer`
The `signed_fil_transfer` server endpoint currently allows the client to specify the following gas parameters:
- `gas_limit`
- `gas_fee_cap`
- `gas_premium`

While the drip amount is controlled by the server, the gas-related fields are taken from the client input without validation, and the server signs the message as-is.
This can be exploited by setting arbitrarily high gas fees, causing the server-controlled wallet to bleed tokens unintentionally.

**Steps to Reproduce:**

1. Call the `signed_fil_transfer` endpoint.
2. Supply a valid recipient address and `nonce` value.
3. Set a large value for `gas_limit`, `gas_fee_cap` and `gas_premium`.
6. Observe that the server signs the transaction.
7. Submit the transaction — observe the signer pays excess gas.

**Possible fixes:**

- Set maximum caps for `gas_limit`, `gas_fee_cap`, and `gas_premium`.

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Set a max limit on all gas values based on observed trend on https://beryx.io/estimate_gas and keeping some buffer.

## Reference issue to close (if applicable)

Closes #274 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation. All new code
      adheres to the team's
      [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [X] I have added tests that prove my fix is effective or that my feature works
      (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes
      should be reflected in this document.

[1]: https://github.com/ChainSafe/forest-explorer/blob/main/CHANGELOG.md

## Summary by CodeRabbit

* **New Features**
  * Added maximum limits for gas parameters (gas limit, gas fee cap, and gas premium) that vary by network.
  * Enforced these maximums when processing Filecoin and ERC-20 token transfers.

* **Bug Fixes**
  * Ensured gas-related parameters cannot exceed network-specific maximum values during transfers.

* **Tests**
  * Added unit tests to verify correct maximum values for each network variant.

### CODE REVIEW

File: src/faucet/constants.rs [hunk 1]
```diff
@@ -166,6 +166,34 @@ impl FaucetInfo {
             Network::Testnet => 314159, // chainlist.org/chain/314159
         }
     }
+
+    /// Returns the maximum allowed gas limit.
+    #[allow(dead_code)]
```
Comment (akaladarshi) [inline src/faucet/constants.rs:171]: Why the `dead_code` ?.

File: src/faucet/constants.rs [hunk 2]
```diff
@@ -166,6 +166,34 @@ impl FaucetInfo {
...
+    pub fn max_gas_limit(&self) -> u64 {
+        match self {
+            FaucetInfo::MainnetFIL => 10_000_000,
```
Comment (akaladarshi) [inline src/faucet/constants.rs:174]: Create constants for these magic numbers as well, something like `CALIBNET_USDFC_GAS_LIMIT_WITH_BUFFER`

**Review by akaladarshi — CHANGES_REQUESTED** [review]
Some comments, otherwise LGTM

File: src/faucet/constants.rs (hunk 1 above)
Comment (sudo-shashank) [reply src/faucet/constants.rs:171]: because it's used only on server side, hence added this to resolve the unused code warning

File: src/faucet/constants.rs (hunk 2 above)
Comment (sudo-shashank) [reply src/faucet/constants.rs]: done

**Review by akaladarshi — APPROVED** [review]
